# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_accept', 'To‘lov qabul qilindi & xizmat faollashtirildi'), ('payment_reject', 'To‘lov rad etildi'), ('manual_subscription_activate', 'Qo‘lda obuna/xizmat faollashtirildi'), ('location_approve', 'Yangi joy tasdiqlandi'), ('review_moderate', 'Sharh moderatsiyasi'), ('user_role_change', 'Foydalanuvchi roli o‘zgartirildi'), ('anti_fraud_ban', 'Anti-fraud cheklovi qo‘yildi')], max_length=50, verbose_name='Bajarilgan amal')),
                ('target_model', models.CharField(max_length=50, verbose_name='Obyekt turi')),
                ('target_id', models.CharField(max_length=50, verbose_name='Obyekt ID')),
                ('details', models.TextField(verbose_name='Batafsil ma’lumot va sabab')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Mas’ul Admin')),
            ],
            options={
                'verbose_name': 'Audit jurnali (Audit Log)',
                'verbose_name_plural': 'Audit jurnallari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Buyurtma tasdiqlandi'), ('booking_reminder', 'Tashrif yaqinlashmoqda'), ('payment_status', 'To‘lov holati'), ('quietpass_status', 'QuietPass obunasi'), ('promo', 'Aksiya va Taklif'), ('system', 'Tizim xabari')], default='system', max_length=30, verbose_name='Turi')),
                ('is_read', models.BooleanField(default=False, verbose_name='O‘qildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
