# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Aksiya sarlavhasi')),
                ('description', models.TextField(verbose_name='Batafsil shartlar')),
                ('discount_percent', models.PositiveIntegerField(default=10, verbose_name='Chegirma foizi (%)')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='locations.location', verbose_name='Joy')),
            ],
            options={
                'verbose_name': 'Aksiya va Taklif (Promotion)',
                'verbose_name_plural': 'Aksiyalar va Takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Ball miqdori (+/-)')),
                ('transaction_type', models.CharField(choices=[('speedtest', 'Speedtest o‘tkazish (+10)'), ('new_location', 'Yangi joy qo‘shish (+50)'), ('photo_review', 'Foto/video sharh yozish (+20)'), ('review', 'Oddiy sharh (+10)'), ('quietpass_discount', 'QuietPass uchun sarflash (-ball)'), ('free_coffee_redeem', 'Bepul kofe kuponi (-ball)'), ('admin_grant', 'Admin tomonidan berildi')], default='speedtest', max_length=30, verbose_name='Amal turi')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('is_anti_fraud_flagged', models.BooleanField(default=False, verbose_name='Shubhali / Tekshirilmoqda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ballar amaliyoti',
                'verbose_name_plural': 'Ballar amaliyotlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
