# Generated by Django 6.1 on 2026-08-14 07:13

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuietPassPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Reja nomi')),
                ('plan_code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Narxi (so‘m)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Amal qilish muddati (kun)')),
                ('discount_percent', models.PositiveIntegerField(default=15, verbose_name='Hamkor joylarda chegirma (%)')),
                ('free_beverage_daily', models.BooleanField(default=True, verbose_name='Kunlik 1 ta bepul kofe/choy')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'QuietPass Rejasi',
                'verbose_name_plural': 'QuietPass Rejalari',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='QuietPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Oylik Pass', max_length=100, verbose_name='Reja nomi')),
                ('price', models.DecimalField(decimal_places=0, default=290000, max_digits=12, verbose_name='To‘langan summa')),
                ('status', models.CharField(choices=[('inactive', 'Nofaol'), ('pending', 'Tasdiqlash kutilmoqda'), ('active', 'Faol (Active)'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quietpasses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.quietpassplan', verbose_name='Tanlangan reja')),
            ],
            options={
                'verbose_name': 'QuietPass Obunasi',
                'verbose_name_plural': 'QuietPass Obunalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=apps.payments.models.generate_tx_id, max_length=50, unique=True, verbose_name='Tranzaksiya ID')),
                ('payment_type', models.CharField(choices=[('booking', 'Stol / Zona bron qilish'), ('quietpass', 'QuietPass obunasi'), ('promoted_listing', 'B2B Reklama / Promoted Listing')], default='booking', max_length=30, verbose_name='To‘lov turi')),
                ('provider', models.CharField(choices=[('click', 'Click Up'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('manual_transfer', 'Karta / Manual chek yuklash'), ('cash', 'Joyida naqd / Karta')], default='payme', max_length=30, verbose_name='To‘lov provayderi')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Summa (so‘m)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda (Pending)'), ('paid', 'To‘langan (Paid / Active)'), ('failed', 'Muvaffaqiyatsiz (Failed)'), ('cancelled', 'Bekor qilingan (Cancelled)'), ('refunded', 'Qaytarilgan (Refunded)'), ('rejected', 'Rad etilgan (Rejected)')], default='pending', max_length=20, verbose_name='To‘lov holati')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='To‘lov cheki / Skrinshot')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi / Rad etish sababi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking', verbose_name='Bog‘langan Booking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('quietpass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.quietpass', verbose_name='Bog‘langan QuietPass')),
            ],
            options={
                'verbose_name': 'To‘lov (Payment)',
                'verbose_name_plural': 'To‘lovlar (Payments)',
                'ordering': ['-created_at'],
            },
        ),
    ]
