# Generated by Django 6.1 on 2026-08-14 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Sarlavha')),
                ('channel_type', models.CharField(choices=[('PHONE', 'Telefon'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('OTHER', 'Boshqa')], default='TELEGRAM', max_length=20, verbose_name='Turi')),
                ('value', models.CharField(help_text='Masalan: +998901234567, @QuietSpaceSupport', max_length=255, verbose_name='Qiymat')),
                ('url', models.URLField(blank=True, verbose_name='Havola')),
                ('icon', models.CharField(default='bi-telegram', max_length=40, verbose_name='Bootstrap Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kontakt kanali',
                'verbose_name_plural': 'Kontakt kanallari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='quietpassplan',
            options={'ordering': ['order', 'price'], 'verbose_name': 'QuietPass Rejasi', 'verbose_name_plural': 'QuietPass Rejalari'},
        ),
        migrations.AddField(
            model_name='quietpassplan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etiladi'),
        ),
        migrations.AddField(
            model_name='quietpassplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('click', 'Click Up'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('manual_transfer', 'Karta / Manual chek yuklash'), ('cash', 'Joyida naqd / Karta')], default='manual_transfer', max_length=30, verbose_name='To‘lov provayderi'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='To‘liq ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('plan_days', models.PositiveIntegerField(default=30, verbose_name='Tarif muddati (kun)')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Summa')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='To‘lov cheki')),
                ('note', models.TextField(blank=True, verbose_name='Izoh / Xabar')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', 'Bog‘lanildi'), ('DONE', 'Tasdiqlandi / Bajarildi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.quietpassplan', verbose_name='Tanlangan tarif')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Obuna so‘rovi',
                'verbose_name_plural': 'Obuna so‘rovlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscriptionrequest', verbose_name='Bog‘langan so‘rov'),
        ),
    ]
