# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qulaylik nomi')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-check-circle', max_length=60, verbose_name='Bootstrap Icon klassi')),
                ('category', models.CharField(choices=[('connectivity', 'Aloqa va Internet'), ('comfort', 'Qulaylik va Muhit'), ('facility', 'Xizmatlar va Inshoot')], default='comfort', max_length=30)),
            ],
            options={
                'verbose_name': 'Qulaylik (Amenity)',
                'verbose_name_plural': 'Qulayliklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Yuridik nomi')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Brend nomi')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN / STIR')),
                ('phone', models.CharField(max_length=30, verbose_name='Bog‘lanish telefoni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='Biznes egasi')),
            ],
            options={
                'verbose_name': 'Biznes / Hamkor',
                'verbose_name_plural': 'Bizneslar / Hamkorlar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Joy nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('coworking', 'Kovorking'), ('cafe', 'Qahvaxona / Tinch Kafe'), ('library', 'Kutubxona'), ('study_zone', 'Study Zone / O‘quv markazi'), ('lounge', 'Work Lounge')], default='coworking', max_length=30, verbose_name='Kategoriya')),
                ('district', models.CharField(choices=[('chorsu', 'Chorsu / Eski shahar'), ('shayxontohur', 'Shayxontohur'), ('yunusobod', 'Yunusobod'), ('mirzo_ulugbek', 'Mirzo Ulug‘bek'), ('mirobod', 'Mirobod'), ('yakkasaroy', 'Yakkasaroy'), ('chilonzor', 'Chilonzor'), ('uchtepa', 'Uchtepa'), ('sergeli', 'Sergeli'), ('olmazor', 'Olmazor'), ('yashnobod', 'Yashnobod')], default='chorsu', max_length=40, verbose_name='Tuman / Hudud')),
                ('address', models.CharField(max_length=300, verbose_name='Aniq manzil')),
                ('landmark', models.CharField(blank=True, max_length=200, verbose_name='Mo‘ljal')),
                ('latitude', models.DecimalField(decimal_places=6, default=41.311081, max_digits=9, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.DecimalField(decimal_places=6, default=69.240562, max_digits=9, verbose_name='Uzunlik (Longitude)')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('description', models.TextField(verbose_name='Joy haqida batafsil')),
                ('working_hours', models.CharField(default='08:00 - 23:00', max_length=100, verbose_name='Ish vaqti')),
                ('is_24_7', models.BooleanField(default=False, verbose_name='24/7 ochiq')),
                ('hourly_price', models.DecimalField(decimal_places=0, default=20000, max_digits=10, verbose_name='1 soatlik narx (so‘m)')),
                ('daily_price', models.DecimalField(decimal_places=0, default=120000, max_digits=10, verbose_name='Kunlik narx (so‘m)')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='locations/covers/', verbose_name='Asosiy rasm')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Promoted / Tavsiya etilgan')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('live_status', models.CharField(choices=[('quiet', '🟢 Tinch va bo‘sh joylar ko‘p'), ('moderate', '🟡 O‘rtacha gavjum'), ('busy', '🔴 Gavjum / Joylar kam')], default='quiet', max_length=20, verbose_name='Hozirgi holat (Live)')),
                ('live_status_updated_at', models.DateTimeField(auto_now=True, verbose_name='Live status yangilangan vaqt')),
                ('current_db_level', models.FloatField(default=45.0, verbose_name='Hozirgi shovqin (dB)')),
                ('avg_download_mbps', models.FloatField(default=120.0, verbose_name='Internet Download (Mbps)')),
                ('avg_upload_mbps', models.FloatField(default=80.0, verbose_name='Internet Upload (Mbps)')),
                ('avg_ping_ms', models.IntegerField(default=8, verbose_name='Ping (ms)')),
                ('rating', models.FloatField(default=4.8, verbose_name='Reyting (1-5)')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Jami tashriflar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='locations', to='locations.amenity', verbose_name='Qulayliklar')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.business', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Ishlash joyi (Location)',
                'verbose_name_plural': 'Ishlash joylari',
                'ordering': ['-is_promoted', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Izoh')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy galereya rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='locations.location', verbose_name='Joy')),
            ],
            options={
                'verbose_name': 'Joy rasmi',
                'verbose_name_plural': 'Joy rasmlari',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zona nomi')),
                ('zone_type', models.CharField(choices=[('quiet_zone', 'Tinch / Jimjit zona (Silent Zone)'), ('open_space', 'Ochiq zal (Open Space)'), ('zoom_booth', 'Zoom / Qo‘ng‘iroq kabinasi (Call Booth)'), ('meeting_room', 'Uchrashuv xonasi (Meeting Room)'), ('terrace', 'Ochiq ayvon / Terassa')], default='quiet_zone', max_length=30, verbose_name='Zona turi')),
                ('noise_level_expected', models.CharField(choices=[('silent', '< 40 dB (Mutlaq tinch)'), ('low', '40-50 dB (Qulay)'), ('normal', '50-65 dB (Faol)')], default='low', max_length=20, verbose_name='Kutiladigan shovqin')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='Sig‘im (odam soni)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.location', verbose_name='Joy')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonalar',
            },
        ),
        migrations.CreateModel(
            name='TableDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50, verbose_name='Stol / Joy raqami')),
                ('has_outlet', models.BooleanField(default=True, verbose_name='Rozetka mavjud')),
                ('hourly_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Maxsus soatlik narx (so‘m)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Foydalanishga tayyor')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='locations.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Stol / Ish o‘rni',
                'verbose_name_plural': 'Stollar / Ish o‘rinlari',
                'unique_together': {('zone', 'table_number')},
            },
        ),
    ]
