# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_mbps', models.FloatField(verbose_name='Download tezligi (Mbps)')),
                ('upload_mbps', models.FloatField(verbose_name='Upload tezligi (Mbps)')),
                ('ping_ms', models.IntegerField(default=10, verbose_name='Ping (ms)')),
                ('source', models.CharField(choices=[('platform_speedtest', 'Sayt orqali Speedtest'), ('user_submission', 'Foydalanuvchi skrinshot/kiritmasi'), ('admin_verified', 'Admin/Ekspert tekshiruvi')], default='platform_speedtest', max_length=30, verbose_name='Manba')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Qurilma ma’lumoti')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('freshness_status', models.CharField(choices=[('fresh', 'Yangi (< 7 kun)'), ('stale', 'Eskirgan (> 30 kun)'), ('needs_verification', 'Qayta tasdiqlanishi kerak')], default='fresh', max_length=30, verbose_name='Yangilik statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='O‘lchov vaqti')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_tests', to='locations.location', verbose_name='Joy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_tests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Internet tezlik testi',
                'verbose_name_plural': 'Internet tezlik testlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoiseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_level', models.FloatField(verbose_name='Shovqin darajasi (dB)')),
                ('duration_seconds', models.PositiveIntegerField(default=10, verbose_name='O‘lchov davomiyligi (soniya)')),
                ('source', models.CharField(choices=[('decibel_meter', 'Mikrofon / O‘lchagich (Web Audio)'), ('user_measurement', 'Foydalanuvchi qaydnomasi'), ('verified_sensor', 'Statsionar sensor')], default='decibel_meter', max_length=30, verbose_name='Manba')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Tasdiqlangan')),
                ('freshness_status', models.CharField(choices=[('fresh', 'Yangi (< 3 kun)'), ('stale', 'Eskirgan'), ('needs_verification', 'Tekshirilishi kerak')], default='fresh', max_length=30, verbose_name='Yangilik statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='O‘lchov vaqti')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noise_tests', to='locations.location', verbose_name='Joy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noise_tests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Shovqin darajasi testi',
                'verbose_name_plural': 'Shovqin testlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
