# Generated by Django 6.1 on 2026-08-14 07:13

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(default=apps.bookings.models.generate_booking_code, max_length=20, unique=True, verbose_name='Buyurtma kodi')),
                ('booking_date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('total_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Davomiyligi (soat)')),
                ('price_per_hour', models.DecimalField(decimal_places=0, default=20000, max_digits=10, verbose_name='1 soatlik narx')),
                ('total_price', models.DecimalField(decimal_places=0, default=20000, max_digits=12, verbose_name='Jami summa (so‘m)')),
                ('status', models.CharField(choices=[('pending', 'To‘lov kutilmoqda (Pending)'), ('confirmed', 'Tasdiqlangan (Confirmed)'), ('checked_in', 'Mijoz kelgan (Checked In)'), ('completed', 'Tugallangan (Completed)'), ('cancelled', 'Bekor qilingan (Cancelled)')], default='pending', max_length=20, verbose_name='Holati')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Bekor qilish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='locations.location', verbose_name='Ishlash joyi')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='locations.tabledesk', verbose_name='Stol / Joy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='locations.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Buyurtma (Booking)',
                'verbose_name_plural': 'Buyurtmalar (Bookings)',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_code', models.CharField(blank=True, max_length=50, verbose_name='Check-in kodi')),
                ('method', models.CharField(choices=[('qr_code', 'QR-kod skanerlandi'), ('code_manual', 'Kodni qo‘lda kiritish'), ('geo_location', 'GPS Geo Check-in')], default='qr_code', max_length=30)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelgan vaqti')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='bookings.booking', verbose_name='Buyurtma')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='locations.location', verbose_name='Joy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Check-in (Tashrif)',
                'verbose_name_plural': 'Check-inlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
