# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Umumiy baho (1-5)')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Sharh matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Rasm / Isbot')),
                ('moderation_status', models.CharField(choices=[('pending', 'Moderatsiya kutilmoqda'), ('approved', 'Tasdiqlangan (Ko‘rinadi)'), ('rejected', 'Rad etilgan')], default='approved', max_length=20, verbose_name='Moderatsiya holati')),
                ('is_verified_visitor', models.BooleanField(default=False, verbose_name='Tasdiqlangan tashrifchi')),
                ('noise_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Shovqin qulayligi (1-5)')),
                ('wifi_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Internet qulayligi (1-5)')),
                ('comfort_rating', models.PositiveSmallIntegerField(default=5, verbose_name='Stol/rozetka qulayligi (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqt')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='locations.location', verbose_name='Ishlash joyi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sharh va Baho',
                'verbose_name_plural': 'Sharhlar va Baholar',
                'ordering': ['-created_at'],
            },
        ),
    ]
