# Generated by Django 6.1 on 2026-08-14 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500, verbose_name='So‘rov matni')),
                ('parsed_filters', models.JSONField(default=dict, verbose_name='Ajratib olingan filtrlar')),
                ('recommended_location_ids', models.JSONField(default=list, verbose_name='Tavsiya qilingan IDlar')),
                ('explanation', models.TextField(blank=True, verbose_name='AI tushuntirishi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_search_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI qidiruv jurnali',
                'verbose_name_plural': 'AI qidiruv jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
